version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 104893874547.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t teste:latest .
      - docker tag teste:latest 104893874547.dkr.ecr.sa-east-1.amazonaws.com/teste:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 104893874547.dkr.ecr.sa-east-1.amazonaws.com/teste:latest